"""Build the collection index from completed validation reports."""

from tapeheads import io


def main() -> None:
    """Link validated videos, trace JSON, diagnostics, and source provenance."""
    encoders = ('wav2vec2', 'muq', 'hubert')
    sources = {
        'espresso': 'Sabrina Carpenter — Espresso',
        'fake_plastic_trees': 'Radiohead — Fake Plastic Trees',
        'bohemian_rhapsody': 'Queen — Bohemian Rhapsody',
        'nature_montage': 'Forest birds, rain, beach, and test signals',
        'chirp_sequence': 'Four chirps, sine, Gaussian noise, silence, and DTMF',
    }
    reports = {
        encoder: io.read_json(
            io.ROOT / f'data/collection-{encoder}-report.json'
        )
        for encoder in encoders
    }
    lines = [
        '# Eight-layer collection studies',
        '',
        'These links refer to local artifacts under `outputs/`, which are excluded',
        'from Git. Reproduce the studies to open them locally. Recorded results and',
        'batch statuses are snapshots of the original runs, not live job status.',
        '',
        'Generated by `python -m tools.report_collection` from validation reports.',
        'Each video progresses through depths 1–8, with up to six remote voices',
        'per layer. The three songs use their full downloaded recordings.',
        'All temporal encoders retain full input context.',
        '',
        '| Input | wav2vec 2.0 | MuQ | HuBERT |',
        '| --- | --- | --- | --- |',
    ]
    for source, title in sources.items():
        cells = [title]
        for encoder in encoders:
            study = reports[encoder]['studies'].get(source)
            if study is None:
                cells.append('Pending')
                continue
            directory = '../' + study['trace'].rsplit('/', 1)[0]
            cells.append(
                f'[Video]({directory}/tapeheads.mp4) · '
                f'[JSON]({directory}/trace.json)'
            )
        lines.append('| ' + ' | '.join(cells) + ' |')
    lines.extend(
        [
            '',
            'Each output directory also contains `mix.wav`, eight fixed-depth',
            '`depth_XX.wav` files, and compressed native layer traces. The root',
            'JSON remains uncompressed. Audio includes all selected recursive',
            'branches; the diagram displays at most 128 connections.',
            '',
            '## Findings and checks',
            '',
            'Completed entries passed native schedule checks, audio reconstruction,',
            'per-hop temporal guards, video timing, and a full FFmpeg decode.',
            'Automated checks and sampled visual inspection are not a full listening',
            'review of every recording.',
            '',
            'Two collection failures were corrected:',
            '',
            '- Long wav2vec rows could exceed the mass tolerance by about 0.000012.',
            '  Adapter `single-pass-sdpa-qk/2` computes softmax in float64 and',
            '  exports float32 probabilities, preserving the existing tolerance.',
            '  Previously validated version 1 layers retain their recorded adapter.',
            '- Resampling the nature montage to 16 kHz left one final sample',
            '  outside its exact labels. The endpoint now includes that sample.',
            '',
            'Four-second fixtures compare all eight extracted layers with independent',
            'native attention for every encoder, with absolute tolerance 0.00001.',
            'This is numerical evidence on fixtures, not an exact full-song comparison.',
            '',
            '| Encoder | Input | Layer | Diagnostic observation |',
            '| --- | --- | --- | --- |',
        ]
    )
    for encoder, report in reports.items():
        for source, study in report['studies'].items():
            for layer in study['diagnostics']:
                for flag in layer['flags']:
                    lines.append(
                        f'| {encoder} | {sources.get(source, source)} | '
                        f'{layer["layer"]} | {flag} |'
                    )
    lines.extend(
        [
            '',
            'Broad accumulated spans follow the requested overlap-continuation rule.',
            'A short native run can be a seek, interruption, or boundary fragment;',
            'its duration alone does not identify a repeated loop.',
            '',
            'Music labels are spectral estimates of opening, contrast, and return,',
            'not verified verses or choruses. Nature and signal labels come from',
            'generator manifests. No lyrics were retrieved.',
            '',
            '## Inputs and reproducibility',
            '',
            'The [download audit](../data/download-audit.json) checks all 14 original',
            'download entries against their hashes, sizes, and decoded metadata.',
            'The [source manifest](../data/sources.json) records recording provenance.',
            'Rain, beach, and traffic are intentional 180-second excerpts.',
            '',
            'The 64.65-second [nature montage](../data/nature_montage.json) contains',
            'forest birds, rain, beach waves, DTMF, a chirp, and a combined passage.',
            'The bird recording is Barracuda1983’s public-domain',
            '[Birds forest](https://commons.wikimedia.org/wiki/File:Birds_forest.ogg).',
            'The combined passage repeats the short bird source as recorded in the manifest.',
            '',
            'Run an encoder with:',
            '',
            '```sh',
            'HF_HUB_OFFLINE=1 .venv/bin/python -m tools.run_collection_studies --encoder muq',
            '```',
            '',
            'Use `--only chirp_sequence` for the signal comparison. Completed traces',
            'are reused; validation runs again. CLAP remains a first-layer experiment',
            'until its shifted-window recursive time mapping is validated.',
            '',
            'Detailed reports:',
            '',
        ]
    )
    for encoder in encoders:
        lines.append(f'- [{encoder}](../data/collection-{encoder}-report.json)')
    (io.ROOT / 'docs/collection-studies.md').write_text('\n'.join(lines) + '\n')


if __name__ == '__main__':
    main()
