"""Build an index and timing summary for validated current-support studies."""

from tapeheads import io

SOURCES = {
    'espresso': 'Sabrina Carpenter — Espresso',
    'bohemian_rhapsody': 'Queen — Bohemian Rhapsody',
    'dodge_image': 'Charles Dodge — He Destroyed Her Image',
    'chirp_sequence': 'Four chirps, tones, noise, silence, and DTMF',
}


def main() -> None:
    """Publish local links only for outputs with completed validation reports."""
    reports = {}
    for encoder in ('muq', 'wav2vec2'):
        path = io.ROOT / f'data/responsive-{encoder}-report.json'
        reports[encoder] = (
            io.read_json(path)['studies'] if path.exists() else {}
        )
    lines = [
        '# Current-support studies',
        '',
        'These links refer to local artifacts under `outputs/`, which are excluded',
        'from Git. Reproduce the studies to open them locally. Recorded results and',
        'batch statuses are snapshots of the original runs, not live job status.',
        '',
        'Generated by `python -m tools.report_responsive` from validation reports.',
        'Each full-length video progresses through depths one, two, and three.',
        'The encoders retain full-input attention context. Each layer can select',
        'up to three remote blocks; individual heads can remain silent.',
        '',
        '| Recording | MuQ | wav2vec 2.0 |',
        '| --- | --- | --- |',
    ]
    for source, title in SOURCES.items():
        cells = [title]
        for encoder, studies in reports.items():
            study = studies.get(source)
            if study is None:
                cells.append('Pending')
                continue
            directory = '../' + study['trace'].rsplit('/', 1)[0]
            cells.append(
                f'[Video]({directory}/tapeheads.mp4) · '
                f'[JSON]({directory}/trace.json)'
            )
        lines.append('| ' + ' | '.join(cells) + ' |')
    lines.extend(
        [
            '',
            'Each directory includes `mix.wav` and full-duration `depth_01.wav`,',
            '`depth_02.wav`, and `depth_03.wav` for comparison at the same timestamp.',
            'Music labels remain blank pending supplied timed lyrics. Chirp labels',
            'come from the generator manifest. See the [design](design.md#current-support-playback)',
            'for thresholds, duplicate handling, and recursive audio rules.',
            '',
            '## Playback checks',
            '',
            'Unsupported percentage measures scheduled remote audio outside the',
            'currently selected block. Run lengths are continuous source reads,',
            'not the lifetime of a voice identifier. Long reads are allowed only',
            'while they remain supported. Short reads can reflect attention shifts.',
            '',
            '| Recording | Encoder | Layer | Unsupported | Median run | Longest run |',
            '| --- | --- | --- | --- | --- | --- |',
        ]
    )
    for encoder, studies in reports.items():
        for source, study in studies.items():
            for layer in study['layers']:
                lines.append(
                    f'| {SOURCES.get(source, source)} | {encoder} | '
                    f'{layer["layer"]} | '
                    f'{layer["unsupported_fraction"]:.2%} | '
                    f'{layer["median_run_seconds"]:.3f} s | '
                    f'{layer["maximum_run_seconds"]:.3f} s |'
                )
    lines.extend(
        [
            '',
            'Completed entries passed native timing and guard checks, recursive audio',
            'reconstruction, and full video decoding. The reports also record near-vertical',
            'native run geometry and 25, 30, and 50 Hz spectral prominence. These frequency',
            'measurements can include musical content; they do not replace listening.',
            'Cadence-frequency energy remains in some outputs, including the chirps.',
            'Removing repeated fade gates does not eliminate every artifact of rapid',
            'source cuts. These results have not had a complete listening review.',
            'The regression suite checks that continuous query cuts do not impose',
            'periodic amplitude gates and that opposite-side child heads remain audible.',
            '',
            'The old Bohemian Rhapsody first-layer schedules played outside current',
            'support for about 43% of remote samples in MuQ and 48% in wav2vec 2.0.',
            'Historical union bounds and retained weak voices explained substantial',
            'stale playback. Current support is now checked at every query.',
            '',
            'Reports: [MuQ](../data/responsive-muq-report.json),',
            '[wav2vec 2.0](../data/responsive-wav2vec2-report.json), and',
            '[previous support audit](../data/responsive-previous-support.json).',
            '',
        ]
    )
    (io.ROOT / 'docs/responsive-studies.md').write_text('\n'.join(lines))


if __name__ == '__main__':
    main()
