"""Run every prepared recording with MuQ and wav2vec2, with resumable reports."""

import argparse
import fcntl
import hashlib
import pathlib
import shutil
import subprocess
import sys
import time

import soundfile

from tapeheads import deep
from tapeheads import io
from tapeheads import render
from tapeheads import selection
from tapeheads import validation
from tools import run_responsive_studies


def configuration() -> selection.SelectionConfig:
    """Return the intermediate continuity preset recorded in every trace."""
    return selection.SelectionConfig(
        tracking_policy='per_head_support',
        entry_alpha=1.5,
        exit_alpha=1.1,
        switch_ratio=1.4,
        max_active_heads=3,
        max_head_blocks=3,
        max_initial_block_seconds=5,
        average_window_seconds=0.5,
        minimum_block_seconds=0.2,
    )


def inputs() -> list[pathlib.Path]:
    """Select one original or full-rate synthetic file per prepared source."""
    result = []
    priority = [
        'chirp_sequence',
        'espresso',
        'bohemian_rhapsody',
        'dodge_image',
        'blue_suede_shoes',
    ]
    for directory in (io.ROOT / 'data/audio').iterdir():
        for name in ('source.flac', 'mono_48000.wav'):
            path = directory / name
            if path.is_file():
                result.append(path)
                break
    return sorted(
        result,
        key=lambda path: (
            priority.index(path.parent.name)
            if path.parent.name in priority
            else len(priority),
            soundfile.info(path).duration,
            path.parent.name,
        ),
    )


def update_index(report: dict) -> None:
    """Expose progress and links without presenting pending work as complete."""
    lines = [
        '# Three-head studies',
        '',
        'These links refer to local artifacts under `outputs/`, which are excluded',
        'from Git. Reproduce the studies to open them locally. Recorded results and',
        'batch statuses are snapshots of the original runs, not live job status.',
        '',
        'Generated by `python -m tools.run_per_head_studies`.',
        'All prepared sources run in full with MuQ and wav2vec2, progressing',
        'through depths one, two, and three. At most three heads each select up to three',
        'blocks. Five-second initial spans extend only under fresh support.',
        '',
        'The ruler marks every 15 seconds; on long recordings, only widely',
        'spaced ticks receive text so labels remain legible.',
        '',
        'Exports use compressed JSON and PCM24 FLAC to fit the available disk.',
        'Native traces contain playback schedules; individual head WAV stems',
        'are omitted. Fixed-depth audio and the final mix remain available.',
        '',
        'Song sections are reference estimates where supplied, not verified',
        'alignment to the downloaded edition. Lyrics have not been retrieved.',
        '',
        '| Recording | Encoder | Status | Outputs |',
        '| --- | --- | --- | --- |',
    ]
    for job in report['jobs']:
        directory = '../' + job['output']
        links = (
            f'[Video]({directory}/tapeheads.mp4) · [JSON]({directory}/trace.json.gz)'
            if job['status'] == 'complete'
            else ''
        )
        lines.append(
            f'| {job["source"]} | {job["encoder"]} | {job["status"]} | {links} |'
        )
    lines.extend(
        [
            '',
            'See [batch status](../data/three-head-batch.json) for errors and settings.',
            '',
        ]
    )
    (io.ROOT / 'docs/three-head-studies.md').write_text('\n'.join(lines))


def worker(
    input_path: pathlib.Path, encoder: str, output: pathlib.Path
) -> None:
    """Generate one complete study and verify its media and source clocks."""
    path = output / 'trace.json.gz'
    if not path.exists():
        deep.analyze(
            input_path,
            output,
            encoder=encoder,
            layers=3,
            voices=3,
            config=configuration(),
            single_pass=True,
            compress=True,
            compact_audio=True,
            block_size=64,
        )
    trace = io.read_json(path)
    assert trace['source']['original_sha256'] == io.sha256(input_path)
    assert all(
        layer['selection']['tracking_policy'] == 'per_head_support'
        for layer in trace['layers']
    )
    if 'video' not in trace['rendering']:
        render.render(path)
    checks = validation.validate(path)
    layers = run_responsive_studies.audit_layers(path)
    assert all(
        layer['unsupported_samples'] == 0 and layer['unselected_samples'] == 0
        for layer in layers
    )
    subprocess.run(
        [
            io.executable('ffmpeg'),
            '-v',
            'error',
            '-xerror',
            '-i',
            str(output / 'tapeheads.mp4'),
            '-f',
            'null',
            '-',
        ],
        check=True,
    )
    io.write_json(
        output / 'validation.json',
        {
            'generator': 'python -m tools.run_per_head_studies',
            'validation': checks,
            'layers': layers,
            'video_decode': 'passed',
            'spectral_diagnostics': run_responsive_studies.cadence_peaks(
                output / 'depth_03.flac'
            ),
        },
    )


def main() -> None:
    """Isolate each model run in a subprocess and preserve progress on failure."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--worker', type=pathlib.Path)
    parser.add_argument('--encoder', choices=('muq', 'wav2vec2'))
    parser.add_argument('--output', type=pathlib.Path)
    arguments = parser.parse_args()
    if arguments.worker:
        if not arguments.encoder or not arguments.output:
            parser.error('--worker requires --encoder and --output')
        worker(arguments.worker, arguments.encoder, arguments.output)
        return
    lock_file = (io.ROOT / 'data/three-head-batch.lock').open('w')
    try:
        fcntl.flock(lock_file, fcntl.LOCK_EX | fcntl.LOCK_NB)
    except BlockingIOError as error:
        raise RuntimeError('A per-head batch is already running') from error
    status_path = io.ROOT / 'data/three-head-batch.json'
    log_directory = io.ROOT / 'data/logs/three-head'
    log_directory.mkdir(parents=True, exist_ok=True)
    digest = hashlib.sha256()
    for path in sorted((io.ROOT / 'tapeheads').glob('*.py')):
        digest.update(path.read_bytes())
    signature = digest.hexdigest()
    previous = (
        io.read_json(status_path) if status_path.exists() else {'jobs': []}
    )
    completed = (
        {
            job['output']
            for job in previous['jobs']
            if job['status'] == 'complete'
        }
        if previous.get('code_sha256') == signature
        else set()
    )
    jobs = [
        {
            'source': path.parent.name,
            'input': str(path.relative_to(io.ROOT)),
            'encoder': encoder,
            'output': f'outputs/{path.parent.name}_{encoder}_threeheads3',
            'status': 'pending',
        }
        for path in inputs()
        for encoder in ('wav2vec2', 'muq')
    ]
    report = {
        'generator': 'python -m tools.run_per_head_studies',
        'code_sha256': signature,
        'jobs': jobs,
        'status': 'running',
    }
    for job in jobs:
        if job['output'] in completed:
            job['status'] = 'complete'
            continue
        if shutil.disk_usage(io.ROOT).free < 2 * 1024**3:
            report['status'] = 'blocked: less than 2 GiB free'
            break
        job['status'] = 'running'
        job['started_at_unix'] = time.time()
        io.write_json(status_path, report)
        update_index(report)
        name = f'{job["source"]}_{job["encoder"]}'
        print(f'Starting {name}', flush=True)
        with (log_directory / f'{name}.log').open('w') as log:
            process = subprocess.run(
                [
                    sys.executable,
                    '-m',
                    'tools.run_per_head_studies',
                    '--worker',
                    str(io.ROOT / job['input']),
                    '--encoder',
                    job['encoder'],
                    '--output',
                    str(io.ROOT / job['output']),
                ],
                cwd=io.ROOT,
                stdout=log,
                stderr=subprocess.STDOUT,
            )
        job['exit_code'] = process.returncode
        job['status'] = 'complete' if process.returncode == 0 else 'failed'
        job['finished_at_unix'] = time.time()
        print(f'{name}: {job["status"]}', flush=True)
        io.write_json(status_path, report)
        update_index(report)
    else:
        report['status'] = (
            'complete'
            if all(job['status'] == 'complete' for job in jobs)
            else 'finished with failures'
        )
    io.write_json(status_path, report)
    update_index(report)


if __name__ == '__main__':
    main()
